name: cicd-giposmart
on:
  push:
    branches:
      - main

jobs:
  my_deploy_job:
    runs-on: ubuntu-latest
    name: deploy to prod
    # These permisions are needed to interact with GitHub's OIDC Tojen endpoint
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - run: npm install -D tailwindcss
      - run: npm install --legacy-peer-deps -D postcss autoprefixer
      - run: npm install --legacy-peer-deps @react-three/fiber @react-three/drei maath react-tilt react-vertical-timeline-component @emailjs/browser framer-motion react-router-dom 
    
      - name: Build Project
        run: |
          npm run build
        env:
          VITE_EMAILJS_SERVICE_ID: ${{ secrets.VITE_EMAILJS_SERVICE_ID }}
          VITE_EMAILJS_TEMPLATE_ID: ${{ secrets.VITE_EMAILJS_TEMPLATE_ID }}
          VITE_EMAILJS_PUBLIC_KEY: ${{ secrets.VITE_EMAILJS_PUBLIC_KEY }}
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::383329440761:role/GitHubActionsRole
          aws-region: us-west-2
          role-session-name: MySessionName
          
      
      - name: Copy files artifacts to s3 bucket
        run: |
          aws s3 sync ./dist s3://giposmart.com
        
