name: cicd-giposmart
on:
  push:
    branches:
      - main

jobs:
  my_deploy_job:
    runs-on: ubuntu-latest
    name: deploy to prod
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - run: npm install -D tailwindcss
      - run: npm install --legacy-peer-deps -D postcss autoprefixer
      - run: npm install --legacy-peer-deps @react-three/fiber @react-three/drei maath react-tilt react-vertical-timeline-component @emailjs/browser framer-motion react-router-dom 
    
