name: cicd-giposmart
on:
  push:
    branches:
      - main

jobs:
  my_deploy_job:
    runs-on: ubuntu-latest
    name: deploy to prod
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      
      - name: Setup Node
        uses: actions/setup-node@v8
      
    
    
